# This is a TOML document.

# route name
[test]
# The stylesheet is mandatory and relative to the directory
# configured with the STYLESHEETS_DIR environment variable.
stylesheet = "testform.xsl"

# An optional "nup" section will print multiple pages on one
# output page.
[test.nup]
# "across" and "down" should be self-explanatory.
across = 3
down = 2
